import Header from "@/components/Header/Header";
import "./globals.css";
import BeforeFooter from "@/components/BeforeFooter/BeforeFooter";
import Footer from "@/components/Footer/Footer";
import { FitlandShoppingContextProvider } from "@/context/fitlandShoppingContext";

export const metadata = {
	title: "Fitland",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="fa" dir="rtl">
			<body className="relative">
				<FitlandShoppingContextProvider>
					{children}
				</FitlandShoppingContextProvider>
			</body>
		</html>
	);
}
