import Header from "@/components/Header/Header";
import "@/app/styles/globals.css";
import BeforeFooter from "@/components/BeforeFooter/BeforeFooter";
import Footer from "@/components/Footer/Footer";
import { FitlandShoppingContextProvider } from "@/context/fitlandShoppingContext";

export const metadata = {
	title: "Fitland",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<FitlandShoppingContextProvider>
			<Header />
			{children}
			<BeforeFooter />
			<Footer />
		</FitlandShoppingContextProvider>
	);
}
